Implement `call_rpc_method()` in `ClientCommandSender`
silicon-heaven/libshvclient-rs pull request #21
Opened 2024-07-23 17:48 UTC by j4r0u53k

This patch adds wrappers for `do_rpc_call()` allowing users to just await final result of a RPC call without long and verbose error handling.

Special methods are implemented for `ls` and `dir`.

2024-07-25 15:46 UTC, syyyr requested changes
There are 5 types of errors:
1) from unbounded_send, which means the library failed to do something
2) "no data from receiver" (due to various unforeseen circumstances, could also technically be a problem in the library)
3) the data sent weren't RpcMessage
4) the RPC call response was an error (not result)
5) the RPC call's result wasn't in the expected format

From my perspective: we should differentiate at least 3 variants in the CallRpcMethodError enum
1-3) InternalError - internal might not be the best way to describe number 3, but from the library user's perspective, they can't really do anything about it (other than print an error message and possibly reinit the app)
4) MethodCallError - the user might care about this, for example, if doing some sort of introspection of the SHV tree
5) ValidationError - this is more like a logical error, this type of error would usually suggest, that as long as the method implementer returns correct data, the problem is that we defined our expected data structure wrongly

2024-07-25 15:46 UTC, syyyr commented on src/client.rs
> +                    CallRpcMethodError::DataError(
I think this should be `ValidationError`

2024-07-25 15:46 UTC, syyyr commented on src/client.rs
> +                    CallRpcMethodError::DataError(
same in call_dir_ls

2024-07-25 15:46 UTC, syyyr commented on src/client.rs
> +            .map_err(|e| data_error(&e.to_string()))
I think the second error should be MethodCallError -> 
![image](https://github.com/user-attachments/assets/353a1fe1-5deb-44c9-bb23-e1ed536c8f05)

2024-07-25 20:46 UTC, syyyr commented on src/client.rs
> +                    CallRpcMethodError::DataError(
1) If it should never happen, then I think the error shouldn't propagate from unbounded_send IMHO. It should just panic. If there's a bug outside our code, or we're out of memory, there's no way we can recover from that.
2) I see. Well, I suppose the user can't really do anything with this error then? Other than just logging I guess.

2024-07-26 08:12 UTC, j4r0u53k commented on src/client.rs
> +                    CallRpcMethodError::DataError(
1. Yes, I think that panicking is appropriate behavior in this case
2. Actually it can and should act like the message might have been delivered to the target (or not) before the disconnection. The appropriate action would depend on the method being called. For a _read_ or an idempotent _set_ operation, it should just wait for connect event and repeat the call. For  _set_ operations that might change the target state in non desired way if called repeatedly, the right way would be to first check the state and then do or do not repeat the call based on the result. Definitely, this kind of error should be distinguished from others.

2024-07-29 09:01 UTC, j4r0u53k commented on src/client.rs
> +                    CallRpcMethodError::DataError(
So I reworked the error type to accept `path`, `method` and `CallRpcMethodErrorKind` enum. Instead of saving the error message inside the enum String, the message is generated in impl of the `Display` trait.

I also tried to find specific and concise names for the errors and ended up with these:

 - `ConnectionClosed` - pretty obvious
 - `InvalidMessage(String)` - couldn't parse an `RpcMessage` out of received `RpcFrame`
 - `RpcError(RpcError)` - got an `RpcError` instead of a result
 - `ResultTypeMismatch(String)` - could not convert result to target data type

2024-07-29 09:04 UTC, j4r0u53k commented on src/client.rs
> +            .map_err(|e| data_error(&e.to_string()))
`RpcError` is pretty much clear about the contained thing.

2024-07-29 09:19 UTC, syyyr commented on src/client.rs
> +                    CallRpcMethodError::DataError(
Nice. Let's go with that.

2024-07-29 09:28 UTC, merged